### ISSUE TITLE
Linux | Manjaro | Getting Install error relating to Krita and seeing UI error in top right corner of notion-app-enhanced 2.0.16-4

### ISSUE THREAD

**Issue by rsramkis** [notion-enhancer/notion-repackaged#6] opened 2021-07-08 12:27 UTC
Hi

When I build the notion-app-enhanced 2.0.16-4 package from the AUR I am experiencing 2 issues which maybe related:

1. I see an error during the install of the package:

`Error in file "/usr/share/applications/krita_jpeg.desktop": "jpeg/jfif" is an invalid MIME type ("jpeg" is an unregistered media type)
Error while configuring notion-app-enhanced'`

2. I'm seeing some kind of misshaped controls in the top right hand corner (see screen shot):

 
![image](https://user-images.githubusercontent.com/14362317/124920309-32470a80-dfc5-11eb-90e8-9bd93ae412a1.png)

**To Try to Troubleshoot:**

- Verify Krita 4.4.3 is installed.
- Krita can open both JPEG and JPG files by default when using File Manager in Gnome.
- I can launch and sign into Notion.

**All Build Messages:**
```
`Preparing...
Cloning notion-app-enhanced build files...
Checking notion-app-enhanced dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building notion-app-enhanced...
==> Making package: notion-app-enhanced 2.0.16-4 (Thu 08 Jul 2021 03:14:01 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found notion-app-enhanced-2.0.16-1.pacman
==> Validating source files with md5sums...
    notion-app-enhanced-2.0.16-1.pacman ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting notion-app-enhanced-2.0.16-1.pacman with bsdtar
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "notion-app-enhanced"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: notion-app-enhanced 2.0.16-4 (Thu 08 Jul 2021 03:15:06 AM)
==> Cleaning up...

Checking keyring...
Checking integrity...
Loading packages files...
Checking file conflicts...
Checking available disk space...
Installing notion-app-enhanced (2.0.16-4)...
Error in file "/usr/share/applications/krita_jpeg.desktop": "jpeg/jfif" is an invalid MIME type ("jpeg" is an unregistered media type)
Error while configuring notion-app-enhanced
Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Updating icon theme caches...
Updating the desktop file MIME type cache...
Transaction successfully finished.`
```

**Desktop Environment**

```
System:
  Host: sol Kernel: 5.4.124-1-MANJARO x86_64 bits: 64 Desktop: GNOME 3.38.4
  Distro: Manjaro Linux
Machine:
  Type: Laptop System: LENOVO v: ThinkPad T450s
  serial: <superuser required>

```

**Comment by rsramkis** [comment] 2021-07-08 12:51
I did some further experimenting which I believe relates to the cause of the problem. This system uses [Firejail](https://man.archlinux.org/man/community/firejail/firecfg.1.en) to sandbox the applications. 

**To get the package to complete install with no errors:**

1. I disable firejail from the system (e.g. sudo firecfg --clean) and then reboot the system.
2. I then re-install the package (assuming that now with no sandboxing the install process now has access to Krita).
3. No errors are received.
4. I launch Notion Enhanced and i can see the minimize\maximize controls are rendered correctly.

![image](https://user-images.githubusercontent.com/14362317/124923998-fdd54d80-dfc8-11eb-8794-62790d39a72a.png)

I remember that the whitesur GTK theme also uses Krita to render those controls. Yet I don't have to shut off sandboxing to install the package. So thought I would share while you research the issue.

**Comment by rsramkis** [comment] 2021-07-12 20:29
@nwatx

In my case Krita was installed. I did some further testing and figured out that it is not Firejail.

The work around starting from the sate where 'Notion is not installed;"

(1) Install Notion from the AUR.

(2) You will see the failed message "Error in file "/usr/share/applications/krita_jpeg.desktop": "jpeg/jfif" is an invalid MIME type ("jpeg" is an unregistered media type) Error while configuring notion-app-enhanced'".

(3) Then chosse package to build\install again and it will succeed with no errors.

(4) The minimized and maximize controls will get rendered correctly.

So I still consider this a bug.

So if you uninstall Notion ... then install from scratch is the error re-producible when installing from the AUR?

**Comment by jamezrin** [comment] 2021-07-12 20:47
The error while installing the package that krita is caused by the notion packages (both enhanced and vanilla) updating the desktop database (via update-desktop-database), this is not a fault of these packages and instead a bug in the krita package.

All you can do regarding this error is to talk to the maintainer of the krita package. This error can be triggered by any package that updates the desktop file database.

Regarding the broken icons/other assets, it's not caused by the krita error, but instead because of a bug in notion-enhancer itself, I'm not sure if there is an issue dedicated to it, but we had a discussion over https://github.com/notion-enhancer/notion-enhancer/issues/467#issuecomment-830469837

I'm going to close this issue as the krita error is not relevant and work is already underway to fix the UI errors. Thanks for reporting it though.

**Closed by jamezrin** 2021-07-12 20:47 UTC
